### ISSUE TITLE
在编辑blog的时候是否可以预览？

### ISSUE THREAD

**Issue by XueWei** [laike9m/My_Blog#10]
登入admin，post新blog编辑的时候，是否可以有格式的工具栏，或者预览。不然一片空白，很难控制格式，甚至插入图片什么的也很困难。

**Comment by laike9m** [comment]
不能。不想弄那么复杂。我都是本地在 Typora 写好再把内容直接粘贴进去。管理界面只适合做一些小的修改，不适合写新文章。

**Comment by XueWei** [comment]
Typora能支持嵌入视频，slide吗？我看到 https://github.com/typora/typora-issues/issues/227 但是我下的mac版并没有找到这个功能。
