### ISSUE TITLE
markdown 转换后的HTML渲染问题

### ISSUE THREAD

**Issue by ttskym** [laike9m/My_Blog#5]
model里是通过github来将markdown转换为HTML格式的，我有个疑问，转换后的HTML是否我可以随意找一个我喜欢的样式表来渲染，而不必用csstwoblog？thanks！

**Comment by laike9m** [comment]
可以的，不过代码高亮那块的渲染得特别注意下，因为网上好多代码高亮的 css 实际上和 github 返回的 html 不匹配，得改一下 css 里的 class 才行

**Comment by ttskym** [comment]
恩，好的，明白了，thanks！
