### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by epluguo** [laike9m/My_Blog#6]
试着跑了下，似乎提供的测试DB结构不对，没有配置完全，css3two_blog_blogpost这个表没有配置，也没有自动创建

**Comment by laike9m** [comment]
你用的 Django 版本是？

**Comment by epluguo** [comment]
Django (1.9.7)
django-contact-form (1.2)
django-taggit (0.19.1)
Pillow (3.2.0)
pip (8.1.2)
requests (2.10.0)
setuptools (18.2)
Unidecode (0.4.19)
uwsgidecorators (1.1.0)

**Comment by laike9m** [comment]
我现在用的1.8，不知道是不是1.9改了什么。你用的什么命令来建表？

**Comment by epluguo** [comment]
我没有建表，我是说你默认提供的sqlite那个db里面是没有对应的表的，也没有什么工具或者自动创建对应的表

**Comment by laike9m** [comment]
这个，当然是没有的了……
数据库的配置在这里 https://github.com/laike9m/My_Blog/blob/master/my_blog/choose_settings.py#L28-L37
我也不是用的 sqlite

**Comment by epluguo** [comment]
粗略看了部分代码，把dev_machines改成包含我的电脑名，就是用SqliteDB了吧
不好意思，我之前没学过Django，昨晚大致看了，似乎数据库的定义直接写在models里面，然后执行某个命令创建的。
但我的Django没有syncdb这个命令
而我看你的表是写在BlogPost里面的，而在setting.py里面的INSTALLED_APPS又没包含这个
我现在要怎样才能顺利的把它跑起来呢？
我可以用runserver把它跑起来，但是因为没有先创建db，所以访问时会一直出错。
我觉得应该在Readme里面写上怎么把它搭建起来的，好囧，还想先看看效果再来看一下代码的..

**Comment by laike9m** [comment]
http://stackoverflow.com/questions/29683494/what-should-i-use-instead-of-syncdb-in-django-1-9
学习没有捷径。如果目的是学习 Django，那查阅文档是不可避免的。

**Comment by laike9m** [comment]
> 粗略看了部分代码，把dev_machines改成包含我的电脑名，就是用SqliteDB了吧
没错。在开发环境下用的 sqlite，线上 PostgreSQL。

**Comment by epluguo** [comment]
找到原因了，可能你的工程是由旧的版本创建的，所以我需要执行
`python manage.py makemigrations css3two_blog`
来创建一个新的migration。
不能直接执行 `python manage.py makemigrations`，这样是检查不到css3two_blog的，因为这是用旧的方式创建的DB,猜测是保留着类似migration脚本之类的文件，然后makemigrations如果不指定APP，会跳过它

**Comment by epluguo** [comment]
找到原因了，可能你的工程是由旧的版本创建的，所以我需要执行
`python manage.py makemigrations css3two_blog`
来创建一个新的migration。
不能直接执行 `python manage.py makemigrations`，这样是检查不到css3two_blog的，因为这是用旧的方式创建的DB,猜测是保留着类似migration脚本之类的文件，然后makemigrations如果不指定APP，会跳过它

**Comment by laike9m** [comment]
嗯，我想起来了，是得加上 `css3two_blog`
