### ISSUE TITLE
A question about how you deploy this project

### ISSUE THREAD

**Issue by gayu-mike** [laike9m/My_Blog#7]
laike9m 你好，我正在写一个 Django 的小项目，从你的博客中学到很多。关于部署有些不明白的地方，希望你能给我一些建议：
1. Nginx + Gunicorn 好像是比较推荐的组合，是否应该再搭配 supervisor 来避免服务器宕机的影响？
2. 关于文章备份，我目前的想法是先在本地写好，再上传。数据库备份就没那么方便了。想听下你的建议。
3. 更新代码，直接利用 git 来更新是否可行呢？
Thanks!

**Comment by laike9m** [comment]
1. 没有用 supervisor，因为这毕竟是个个人项目，监控就免了（其实是因为访问量低

2. 文章我都是在本地写然后开 admin 添加进去，因为显然本地编辑器体验更好。推荐 Typora。至于文章备份，是有另一个 repo 的：https://github.com/laike9m/media。这个就是不定期会去 update 一下，当然弄成某种自动化的也不是不行。

3. 代码是用 Git 更新的，好像也没什么别的方法更新吧……在 virtualenv 里面我弄了一个 hook，在切到 env 的时候直接完成 git pull + collectstaticfile.

**Comment by gayu-mike** [comment]
非常感谢你的无私帮助 :-)
